name: quran_exams_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  quran: 1.2.8
  cloud_firestore: ^5.4.0
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  cached_network_image: ^3.4.0
  provider: ^6.1.5+1
  shared_preferences: ^2.2.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.jpg"

flutter:
  uses-material-design: true

  fonts:
    - family: 'Uthmanic'
      fonts:
        - asset: assets/fonts/hafs18.ttf