name: Build and Release Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. سحب الكود
      - uses: actions/checkout@v3

      # 2. تهيئة الجافا
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. تثبيت الفلاتر سحابياً بـ إصدار محدد لإجبار السيرفر على التحميل الفوري
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.22.x' # تحديد الإصدار يمنع السيرفر من عمل Skip 🎯

      # 4. سحب مكاتب المشروع
      - name: Get Dependencies
        run: flutter pub get

      # 5. أمر بناء الـ APK
      - name: Build APK
        run: flutter build apk --release

      # 6. الرفع الفوري كـ روليز جديد تماماً
      - name: Upload APK to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          tag_name: v1.0.1 # 🌟 رقم جديد بالملي لتصفير كاش غيت هاب الملعون
          name: الإصدار المطور والمصحح 📖
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}